<?php
echo "<footer>
  <hr>
  <p id="footer-title">Our Group Members:</p>
  <p id="footer-mailto"><a href="mailto:103608973@student.swin.edu.au">Gerard Go</a><a href="mailto:103590300@student.swin.edu.au">Koby Bremner</a><a href="mailto:103994656@student.swin.edu.au">Jinxi Xu</a><a href="mailto:102579049@student.swin.edu.au">Josh Willcock</a><a href="mailto:103075742@student.swin.edu.au">Christian Cheng</a></p> 
</footer>";
?>