<?php
if (defined('INDEX')) {
    echo "<header><h1 class=\"title\">MMO RPG</h1></header>";
}
if (defined('QUIZ')) {
    echo "<header><h1 class=\"title\">MMORPG - Quiz</h1></header>";
}
if (defined('TOPIC')) {
    echo "<header><h1 class=\"title\">MMORPG - Topic Description</h1></header>";
}
if (defined('PHPENHANCEMENTS')) {
    echo "<header><h1 class=\"title\">MMORPG - PHPENHANCEMENTS</h1></header>";
}
?>