<?php
if (defined('INDEX')) {
    echo "<header><h1 class=\"title\">MMO RPG</h1></header>";
}
if (defined('QUIZ')) {
    echo "<header><h1 class=\"title\">MMORPG - Quiz</h1></header>";
}
if (defined('TOPIC')) {
    echo "<header><h1 class=\"title\">MMORPG - Topic Description</h1></header>";
}
if (defined('PHPENHANCEMENTS')) {
    echo "<header><h1 class=\"title\">MMORPG - PHP Enhancements</h1></header>";
}
if (defined('MARKQUIZ')) {
    echo "<header><h1 class=\"title\">MMORPG - Mark Quiz</h1></header>";
}
if (defined('ATTEMPTS')) {
    echo "<header><h1 class=\"title\">MMORPG - Attempts</h1></header>";
}
if (defined('LOGIN')) {
    echo "<header><h1 class=\"title\">LOGIN TO ACCESS ATTEMPTS</h1></header>";
}
?>